### PR TITLE
Update lab-01.rst

### PR DESCRIPTION
**Pull request by Sergie7**
Correction to templates:

using code-eval rather than math, for correct implementation.  scripts referenced with code-eval have been proposed in a separate pull request.

### CODE REVIEW

**Comment by moorepants** [comment]
I don't think that you can add new files to an existing pull request via the website. So I think you should add all the new matlab files first via one or more pull requests. Then after those are merged, you can make the pull request to edit the lab file.

**Comment by Sergie7** [comment]
> I don't think that you can add new files to an existing pull request via the website. So I think you should add all the new matlab files first via one or more pull requests. Then after those are merged, you can make the pull request to edit the lab file.

**Comment by Sergie7** [comment]
I want to edit this pull request to remove the template I originally typed using the "math".  It asks me to commit directly to the branch "Update lab-01.rst" or open a separate pull request.  Committing directly to this branch right will still keep everything in my pull request right?

**Comment by moorepants** [comment]
Yes. That's fine.

**Comment by Sergie7** [comment]
I edited a script in a separate pull request.  I think the correction will allow this pull request to go pass the checks.  The check failure details said there was an issue finding said script using code-eval.

**Comment by moorepants** [comment]
I just updated this with the other changes. We'll see if it builds.

**Pull request merged**
